# Faction Information ---------------------------------
faction.Data <- list(
  "Kukulkani" = list(
    "front.Blurb" = "Ancient aliens whose visit to Earth inspired Aztec and Mayan cultures, a force of Kukulkani crusaders have arrived at Samaria seeking slaves and an ancient foe.",
    "back.Blurb" = "Armed with advanced technology and able to harvest energy upon slaying enemies, a Kukulkani force can swiftly snowball out of control.",
    "pros" = "<ul><li>Powerful and flexible rituals</li><li>Powerful single units</li><li>Bioenergy Snowballing</li></ul>",
    "cons" = "<ul><li>General low durability</li><li>Reliant on bioenergy</li></ul>",
    "header.Img" = "k3_back.jpg",
    "back.Img" = "faction_icons/logo_kukulkani.png",
    "sub.Faction" = c("Unaligned")
    ),
  "Brood" = list(
    "front.Blurb" = "Remnants of biological experiments on Samaria by the NorTec corporation, the Brood are prime examples that life finds a way.",
    "back.Blurb" = "While the Brood generally swarms of fragile units, they make up for it by having access to regeneration.",
    "pros" = "<ul><li>Flexible list building</li><li>Regeneration</li></ul>",
    "cons" = "<ul><li>Lower base HP</li></ul>",
    "header.Img" = "brood_back.jpg",
    "back.Img" = "faction_icons/logo_brood_0.png",
    "sub.Faction" = c("Unaligned","Broodmere Spawn","Delta Broodfolk","Progeny")
  ),
  "C.O.R.E" = list(
    "front.Blurb" = "Once an automatic NorTec mining system, the C.O.R.E AI was wounded and driven insane by the Dragyri Shadow Caste. Now the C.O.R.E seeks only to convert all life on Samaria into fuel.",
    "back.Blurb" = "With an arsenal of brutal weapons and the ability to repair downed units, C.O.R.E forces can be a nightmare to face.",
    "pros" = "<ul><li>Immune to abilities that require living</li><li>Powerful ranged attacks</li></ul>",
    "cons" = "<ul><li>Requires careful placement of command units</li><li>Low defense</li></ul>",
    "header.Img" = "core_back.jpg",
    "back.Img" = "faction_icons/logo_core.png",
    "sub.Faction" = c("Unaligned")
  ),
  "Skarrd" = list(
    "front.Blurb" = "Twisted and monstrous human tribes, the Skarrd engage in horrific body modification and mutilation on a daily basis.",
    "back.Blurb" = "Skarrd tribes grant their forces access to powerful themed abilities, making each tribe a unique force.",
    "pros" = "<ul><li>Able to take damage to gain abilities</li><li>Powerful thematic abilities</li></ul>",
    "cons" = "<ul><li>Fragile</li><li>Very limited ranged attacks</li></ul>",
    "header.Img" = "skarrd_back.jpg",
    "back.Img" = "faction_icons/logo_skarrd.png",
    "sub.Faction" = c("Unaligned","Blood","Decay","Toxic","Metamorphosis")
  ),
  "Dragyri" = list(
    "front.Blurb" = "Remnants of a powerful spacefaring race, the Dragyri on Samaria are now a shamanistic feudal culture.",
    "back.Blurb" = "Flanked by their lowborn slaves, Dragyri Trueborns are incredibly powerful elites and compose the majority of a Dragyri force.",
    "pros" = "<ul><li>Different elements have different strengths</li><li>Regeneration</li></ul>",
    "cons" = "<ul><li>High cost units</li><li>Elements have different weaknesses</li></ul>",
    "header.Img" = "drag_back.jpg",
    "back.Img" = "faction_icons/logo_dragyri.png",
    "sub.Faction" = c("Ice","Fire","Air","Earth","Shadow")
  ),
  "Outcasts" = list(
    "front.Blurb" = "Those humans who live outside the walls of New Ashkelon and avoid the predations of the Skarrd survive in the barren wasteland and form the nebulous Outcast.",
    "back.Blurb" = "Surviving in the wasteland has toughened the Outcasts.",
    "pros" = "<ul><li>Barrow Slavers can apply debuffs to any faction</li><li>Unit buffs from salvage</li></ul>",
    "cons" = "<ul><li>-</li></ul>",
    "header.Img" = "outcast_back.jpg",
    "back.Img" = "faction_icons/logo_outcasts.png",
    "sub.Faction" = c("Unaligned","Scavengers","Court of Freeton","Barrow Slavers","Saltflat Nomads")
  ),
  "Forsaken" = list(
    "front.Blurb" = "Residents of the city of New Ashkelon, the Forsaken follow holy scripture to escape the purgatory that is Samaria.",
    "back.Blurb" = "Incredibly varied, a Forsaken force has access to nearly every ability and weapon in the game.",
    "pros" = "<ul><li>Many ranged options</li><li>Many flexible units</li></ul>",
    "cons" = "<ul><li>Few powerful single units</li></ul>",
    "header.Img" = "forsaken_back.jpg",
    "back.Img" = "faction_icons/logo_forsaken.png",
    "sub.Faction" = c("Unaligned","Isaac","Mary","Luke","Joan","John","Mark","Heretic","Prevailer")
  )
)

# Rules Reference ---------------------------------
rules.Reference <- list("Rules" = c("Combat Reflexes",
                                    "Commander",
                                    "Critical Strike (x)",
                                    "Decapitate",
                                    "Furious Charge",
                                    "Fire",
                                    "Fire Counter",
                                    "Inspiring",
                                    "Toxic",
                                    "Toxic Counter",
                                    "Crack Shot",
                                    "Point Blank",
                                    "Proximity Strike (x)",
                                    "Sunder Armor",
                                    "Sunder Counter",
                                    "Quick Draw",
                                    "Order (x) (y)",
                                    "Enhanced Optics",
                                    "Reconnaissance",
                                    "Hit and Run",
                                    "Infiltrate",
                                    "Strider",
                                    "Knockdown (x)",
                                    "Stun",
                                    "Stun Counter",
                                    "Survivalist",
                                    "Medic",
                                    "Dying Counter",
                                    "Paralysis",
                                    "Paralyzed Counter",
                                    "Restoration",
                                    "Bleed",
                                    "Bleed Counter",
                                    "Extreme Damage",
                                    "Finishing Blow",
                                    "Retaliation",
                                    "Superior Maintenance (x)",
                                    "Enhance (x) (y)",
                                    "Guard",
                                    "Sniper (x)",
                                    "Explosive End (x)",
                                    "Reaction Strike",
                                    "Victimize",
                                    "Human Shield",
                                    "Final Strike",
                                    "Enviro Filters",
                                    "Parry",
                                    "Riposte (x)",
                                    "Tough as Nails",
                                    "Aren's Playthings",
                                    "Bio-Gen (x)",
                                    "Controller (x)",
                                    "Control Counter",
                                    "Mental Link (x)",
                                    "Unusual Clients (x)",
                                    "Upgrade (x)",
                                    "Latch On (AG #x)",
                                    "Non-Living",
                                    "Program (x)",
                                    "Regeneration",
                                    "Regeneration Counter",
                                    "Vault",
                                    "Berserk",
                                    "Berserk Counter",
                                    "Exhaustion Counter",
                                    "Pull (x)",
                                    "Rage",
                                    "Deflection",
                                    "Immune (x)",
                                    "Infiltrate",
                                    "Rend",
                                    "Trigger Happy",
                                    "Unknown Purpose",
                                    "Blind",
                                    "Blind Counter",
                                    "Immobilize",
                                    "Immobilized Counter",
                                    "Patch 'Em Up",
                                    "Volative Enhancement (x)",
                                    "First Generation",
                                    "Parting Blow",
                                    "Psychogenic Neophyte",
                                    "Sidestep",
                                    "Brutal",
                                    "Matched Set (x)",
                                    "Maximo's Guardian",
                                    "Rage Counter",
                                    "Unstoppable",
                                    "Weakend Resolve Counter",
                                    "Playing Possum",
                                    "Possum Counter",
                                    "Whiplash",
                                    "Whiplash Counter",
                                    "Animosity (x)",
                                    "Knockback (x)",
                                    "Stoneskin",
                                    "Backstab",
                                    "Corrosion",
                                    "Corrosion Counter",
                                    "Sadistic",
                                    "Lucky",
                                    "Luck Counter",
                                    "Cabal (x)",
                                    "Executioner",
                                    "Good Aim",
                                    "Burst",
                                    "Guerrilla Tactics",
                                    "Masochist (x)",
                                    "AJAX Overcharge",
                                    "Ambush",
                                    "Death From Above",
                                    "Conduction",
                                    "Stealth Counter",
                                    "Continuous",
                                    "Horrific Visage",
                                    "Fueled by Combat",
                                    "Psychogenic Master",
                                    "Assassination",
                                    "Never Panic",
                                    "Empower",
                                    "Suppression",
                                    "Horrible Death",
                                    "Blinding Shockwave",
                                    "Oath of Fury",
                                    "Oath Counter",
                                    "Adaptability",
                                    "Disruption",
                                    "Disruption Counter",
                                    "Rot",
                                    "Rot Counter",
                                    "Crush",
                                    "Stim Injection",
                                    "Harpy Queen",
                                    "Worm Father",
                                    "Power Generator",
                                    "Shockwave",
                                    "Bannerman of John",
                                    "Devastating Charge",
                                    "Combat Tactics",
                                    "Smoke Bomb",
                                    "Smoke Cloud",
                                    "Mark For Death",
                                    "Marius' Cherub",
                                    "Skylancer Jets",
                                    "Shield Formation",
                                    "Consume Brood",
                                    "Swarm",
                                    "Pack Attack",
                                    "Brood Mind",
                                    "For The Swarm",
                                    "Burrow",
                                    "Burrow Counter",
                                    "Metabolize",
                                    "Energize Counter",
                                    "Scavenge",
                                    "Scavenge Counter",
                                    "Defiance",
                                    "Elusive",
                                    "Field Order (x) (y)",
                                    "Extinguish",
                                    "Distraction",
                                    "Vigilance",
                                    "Psychogenic Invoker",
                                    "Resourceful",
                                    "Bloodlust",
                                    "Bloodlust Counter",
                                    "Ghost in the Machine",
                                    "Dominique's Playthings",
                                    "Ion Shield",
                                    "Psychogenic Resolve (x)",
                                    "Irradiated",
                                    "Enhance (x) (y)",
                                    "Frenzied",
                                    "Contagion",
                                    "Virulent Fumes",
                                    "My Pretty Toys",
                                    "We Are The Wind",
                                    "Master of Air",
                                    "Taskmaster (x)",
                                    "Shard Scatter (x)",
                                    "Shard Field (x)",
                                    "Redirection",
                                    "Unforgiving Ground",
                                    "Momentum",
                                    "Centered Focus",
                                    "Unstable (x)",
                                    "Fading Spirit",
                                    "Phantasmal",
                                    "Emberspark",
                                    "Our Vengeance Is Eternal!",
                                    "Xenosathic Conduit",
                                    "Heart of the Flame",
                                    "Shard Walk",
                                    "Servant of the Flame",
                                    "Three Steps Ahead",
                                    "Chilling Aura",
                                    "Darkness Consume You!",
                                    "Spike Shower",
                                    "Nightmare Aura",
                                    "Emotionless",
                                    "Blink",
                                    "Echoes of Death",
                                    "Death Echo Counter",
                                    "Reconstruction",
                                    "Scrap Counter",
                                    "Superior Gang-Up",
                                    "Diagnostics",
                                    "Universal Redundancies",
                                    "Bio-Enhance (x)",
                                    "Bio-Energy Counter",
                                    "Life-Siphon",
                                    "Scion of the Moon",
                                    "Construct Mastery",
                                    "Technomancy",
                                    "Ritual Engine (x)",
                                    "Improved Climb",
                                    "Master of Death",
                                    "Ritual Sacrifice",
                                    "Solar Balance",
                                    "Lunar Balance",
                                    "Technomantic Apprentice (x)"
                                    ),
                        "Definition" = c("Enemies never gain bonuses for Charging or Gang-Up against this model. This model may stand up from prone for no AP cost.",
                                         "This model counts as having all Squadlink Keywords.",
                                         "This attack Critically Hits on attack rolls of (x) or less.",
                                         "If this attack Critically Hits, its target loses 1 additional HP.",
                                         "This model gains an additional +1 AS and +1 PW to charge attacks.",
                                         "Models hit by this attack gain 1 Fire Counter.",
                                         "This model may spend 1 AP to roll a d20. On a result of 10 or less remove the Fire Counter. This model suffers 1 automatic PW: 4 hit for each AP it spends on actions other than removing the Fire Counter. Resolve these automatic hit(s) after the action is completed. A model may only have 1 Fire Counter at any time.",
                                         "Other non-Character models this model Squadlinks with gain +1 AS to all attacks, and an additional +1 PW to melee attacks.",
                                         "Models hit by this attack gain 1 Toxic Counter.",
                                         "This model suffers penalties based on the number of Toxic Counters on it. All Toxic Counters are removed at the end of this model’s activation. All negatives are cumulative.</br>1+ Counters: -2 AS to all attacks</br>2+ Counters: -2 PW to all attacks</br>3+ Counters: Each time this model spends AP on attacks, it suffers 1 automatic PW: 2 hit before resolving those attacks.",
                                         "This model ignores Light Cover, and treats Heavy Cover as Light Cover",
                                         "This ranged attack may be used while engaged. If used while engaged, this attack must target an enemy this model is engaged with.",
                                         "When this attack is selected, place the Blast(x) Template anywhere completely in range of this attack. Make 1 separate attack roll against each enemy model under the template. Only the initial attack roll may suffer Malfunction or gain the benefits of Aiming.",
                                         "Models hit by this attack gain 1 Sunder Counter.",
                                         "This model suffers -2 AR. A model may only have 1 Sunder Counter at any time.",
                                         "This model may spend 1 AP to make an Aimed ranged attack, or move up to their MV value and make a ranged attack.",
                                         "When this model squadlinks with (x), those models gain (y) this activation.",
                                         "When this model Aims, it gains an additional +1 AS, ignores Light Cover, and treats Heavy Cover as Light Cover for this attack.",
                                         "This model may always choose to deploy using its Infiltrate special ability before any other models using the Infiltrate special ability. It and any other friendly models with the Infiltrate special ability that share its Squadlink keyword may deploy up to 6” away from an enemy Deployment Zone instead of the normal distance allowed.",
                                         "When this model kills a model with an attack, it may immediately gain 1 AP to Move. This move action ignores the rules for Breaking Free and may result in a charge.",
                                         "This model is only deployed after all non-Infiltrating models have been deployed. This model may be deployed anywhere on the battlefield that is at least 12” from an enemy deployment zone.",
                                         "This model ignores the Rough keyword of terrain pieces. This model may stand up from prone for no AP cost.",
                                         "When this attack hits a model, after AR Saves are made, roll a d20. If the number rolled is equal to or under (x) then the target is Knocked Prone. Melee attacks suffer -2 to (x) for every size smaller the attacking model is than the target and +2 to (x)for every size larger the attacking model is than the target.",
                                         "Models hit by this attack gain 1 Stun Counter.",
                                         "The next time this model activates, it immediately loses 1 AP, and then removes 1 Stun Counter. A model may only have 1 Stun Counter at any time.",
                                         "If this model only spends AP on Movement during its activation, it may go On Hold for free at the end of that activation.",
                                         "Other friendly, Living, models reduced to 0 HP while within 8” of this model are not killed, but instead gain 1 Dying Counter.",
                                         "This model is prone and may not activate. If this model would ever lose HP, it is killed. At the start of the Lingering Effects Phase, if a friendly, non-dying, model with Medic is not within 8”, kill this model. Remove this Counter if this model is ever healed.",
                                         "Models hit by this attack gain 1 Paralyzed Counter.",
                                         "When this model activates, roll a d20. On a 11 or greater it loses 1 AP and must roll again, continuing until a 10 or less is rolled, or it runs out of AP. Once this is complete, remove all Paralyzed Counters.",
                                         "This attack may target, and automatically hit, friendly models. Friendly models hit by this attack suffer no damage and instead heal 1 HP. A model may only be healed by Restoration once per game.",
                                         "Living Models hit by this attack gain 1 Bleed Counter.",
                                         "During the Lingering Effects Phase roll a d20. On a result of 11+ this model loses 1 HP, otherwise, remove the Bleed Counter. A model may only have 1 Bleed Counter at any time.",
                                         "Models that fail an AR Save caused by this attack lose 2 HP.",
                                         "This attack gains 1 additional power multiplier and Extreme Damage when targeting models that are prone.",
                                         "When an enemy misses this model with a melee attack, and this model has not been killed, after all attacks are resolved this model may select 1 of its attacks and perform it against that enemy.",
                                         "(x) times per game, when a malfunction is rolled from a non-psychogenic attack, that model may ignore the malfunction. This ability functions even if this model is killed.",
                                         "When this model is deployed, choose up to 6 (x). Those models gain (y).",
                                         "When a friendly model within 4” and line of sight is targeted by a non-template ranged attack, this model may become the target of the attack instead (Guard may not trigger another model’s Guard ability).",
                                         "When this model Aims, its ranged attacks gain Critical Strike(x), where (x) is equal to this model’s Sniper(x) value.",
                                         "When this model is killed, place a Blast(2) template with the center hole anywhere completely over this model’s base. Each model under the template suffers an automatic hit from (x), and then this model is removed (this is a Template Attack).",
                                         "Once per round, when an enemy comes within range of this attack, this model may perform this attack for free against that enemy. This free attack occurs before charge attacks are resolved.",
                                         "Models hit by this attack gain 1 Panic Counter.",
                                         "When this model is hit by an enemy non-template attack, it may force 1 friendly model within 4” to be hit by the attack instead. That attack gains an additional power multiplier for this hit (Hits from Human Shield cannot trigger Human Shield).",
                                         "When this model would be killed, it may make a PS Check. On a success it may select and perform 1 of its attacks before being removed.",
                                         "This model ignores Smoke Clouds",
                                         "When this model is targeted by melee attacks, after attack rolls are made, this model may make an AS Check. If the check is successful it may discard 1 non-critical hit from those attacks.",
                                         "This model adds (x) to all AS Checks for the Parry special ability. When it successfully Parries, it may immediately make 1 melee attack against the attacking enemy.",
                                         "This model ignores Critical AR Failure.",
                                         "When this model is deployed, two C.O.R.E.hound models are immediately deployed within 4” of it.",
                                         "This model possesses (x) Brood Bio-Gens, chosen before the beginning of the game. Some models will have specific Bio-Gens named as the (x).",
                                         "During the Preparation Phase, this model gains (x) Control Counters. It may have a maximum of (x) Control Counters at any time.",
                                         "Control Counters are utilized by models with the Program(x) special ability. See those model’s individual Stat Cards for more information.",
                                         "All friendly (x) models use this model’s PS in place of their own PS for all PS Checks, taking into effect all current modifiers on both models.",
                                         "This Bounty Hunter may only be included in (x) faction forces.",
                                         "This model possesses (x) C.O.R.E. Upgrades, chosen before the beginning of the game. Some models will have specific Upgrades named as the (x)",
                                         "Attacks from this assault group cannot be selected as normal. If all attacks from (AG#x) hit the same target with the same attack action then Latch On is triggered. When Latch On is triggered, the target immediately suffers an automatic hit from this attack. Until the end of this model’s activation, it may spend 1 AP to cause additional automatic hits to the target with this attack.",
                                         "This model may never gain Panic Counters. This model’s PS may never be modified by enemy effects.",
                                         "This model may remove 1 Controller Counter from a friendly model it is squadlinking with. If it does so, it gains (x) this activation. Each Program may only be selected once per activation.",
                                         "At the start of this model’s activation, it heals 1 HP. When this model is reduced to 0 HP it is not killed, but instead gains 1 Regeneration Counter.",
                                         "This model is prone, and may not perform attacks. If this model would ever lose HP, it is killed. Remove this Counter if this model is ever healed.",
                                         "Once per activation, this model may spend 1 AP to immediately move their MV value, ignoring terrain as well as intervening models. If this move results in a charge, this model gains and additional +1 AS and +1 PW to the charge attack.",
                                         "This model may spend 1 AP to gain 1 Berserk Counter. A model may only have 1 Berserk Counter at any time.",
                                         "This model gains +1 AS, +1 PW, an additional power multiplier to melee attacks, and the Never Panic special ability. After any activation in which this model did not make a melee attack they gain an Exhaustion Counter.",
                                         "This model suffers -1 AP per Exhaustion Counter. If this model activates with 0 AP due to Exhaustion Counters, remove all Berserk and Exhaustion Counters and end their activation.",
                                         "When this attack hits a model, after AR Saves are rolled, roll a d20. If the number rolled is equal to or under (x) then the model hit is moved directly toward this model until it is in contact or comes in contact with another model or a terrain piece it cannot cross. Reduce (x) by 2 for every size smaller the attacking model is than the target and increase (x) by 2 for every size larger the attacking model is than the target.",
                                         "This model’s melee attacks gain +2 PW for each missing HP.",
                                         "When this model is targeted by a non-template ranged attacks, after attack rolls are made, this model may make an AS Check. If the check is successful you may disregard 1 non-critical hit against this model from those attacks.",
                                         "This model may never be affected by (x).",
                                         "This model is only deployed after all non-Infiltrating models have been deployed. This model may be deployed anywhere on the battlefield that is at least 12” from an enemy deployment zone.",
                                         "If all attacks from this assault group hit the same target, they gain 1 additional power multiplier for this attack.",
                                         "At the start of each activation, this model must make a PS Check. On a failure it does not activate as normal, does not move, and instead uses its activation to immediately to make AG#1 Ranged Attacks upon the nearest target with a different model name in Range and Line of Sight. If no targets are available when the PS Check is failed, this model goes On Hold and ends its activation.",
                                         "This model cannot attack or interact with Objective Markers.",
                                         "Models hit by this attack gain 1 Blind Counter.",
                                         "This model suffers -4 AS. Remove the Blind Counter at the end of this model’s activation. A model may only have 1 Blind Counter at any time.",
                                         "Models hit by this attack gain 1 Immobilized Counter.",
                                         "This model suffers -1 MV per Immobilized Counter. Remove all Immobilized Counters at the end of a model’s activation.",
                                         "This model may spend 1 AP when in base contact with a Living model and attempt a PS Check. On a success, the contacted Living model heals 1 HP. If the check is failed, the target takes 1 HP of damage instead.",
                                         "Other non-Character models this model squadlinks with may gain (x) this activation. If this is done, that model loses 1 HP at this end of this activation. A model may only benefit from Volative Enhancement once per activation.",
                                         "This model does not count as Brood or Broodfolk, ye remains a friendly model to its force for all other purposes.",
                                         "Enemy models that Break Free from engaging this model are automatically targeted and attacked using this attack type before they are allowed to move the model away.",
                                         "This model may spend 1 AP to cast the (x) psychogenic.",
                                         "When this model is hit by a non-critical hit from a melee or template attack, and is not prone, roll a d20. On a roll of 12 or less the attack roll is discarded.",
                                         "The Parry special ability may not be used against this attack.",
                                         "This model may only be included in a force that also includes (x).",
                                         "Once per round, if Maximo is within 8” and targeted by an attack, place this model in contact with Maximo. It becomes the new target of the attack. This ability cannot be used if there is no space to place Phadras. When Maximo is killed, or gains a Possum Counter, this model gains 1 Rage Counter.",
                                         "his model suffers -2 AS, but gains +2 PW to all melee attacks. A model may only have 1 Rage Counter at any time.",
                                         "Whenever this model would be reduced to 0 HP, it may make a PS Check. On a success, this model remains at 1 HP, but gains 1 Weakened Resolve Counter.",
                                         "This model suffers -4 PS. Weakened Resolve Counters are cumulative.",
                                         "The first time this model would be reduced to 0 HP, you may instead give it 1 Possum Counter.",
                                         "This model may not activate, and may not be targeted by attacks. During the Preparation Phase of any round, this model must make a PS Check, on a failure, remove its Possum Counter. During the Preparation Phase, this model may also voluntarily remove its Possum Counter.",
                                         "Models hit by this attack who pass their AR Save gain 1 Whiplash Counter.",
                                         "The next time this model activates, it immediately loses 1 AP per Whiplash Counter, and then all Whiplash Counters are removed.",
                                         "This model may not be included in any force that has a model named (x).",
                                         "When this attack hits a model, after AR Saves are made, roll a d20. If the number rolled is equal to or under (x) then the target is moved directly away 6”. Melee attacks suffer -2 to (x) for every size smaller the attacking model is than the target and +2 to (x) for every size larger the attacking model is than the target.",
                                         "When this model is hit by a non-critical attack, roll a d20. On a 10 or less the model suffers one less HP of damage from the attack, but could still be affected by any weapon abilities triggered by the hit (Knockdown, Sunder Armor, etc.)",
                                         "This model gains +2 AS and +2 PW to all attacks made against a model that has not activated this round.",
                                         "Models hit by this attack gain 1 Corrosion Counter.",
                                         "his model suffers -1 AR per Corrosion Counter. During the Lingering Effects Phase, roll 1d20 for each Corrosion Counter, removing it on a roll of 10 or less.",
                                         "This model’s melee attacks gain +2 PW when targeting a model with a Panic Counter.",
                                         "This model begins the game with 1 Luck Counter",
                                         "This model may discard this counter at any time to re-roll 1 attack roll or AR Save it performs.",
                                         "If this model begins its activation within 8'' of (x), it may re-roll 1 Attack Roll this activation",
                                         "This model gains +2AS when targeting Prone models.",
                                         "When this model makes an Aimed Ranged Attack, it gains an additional +1 AS to that attack. Additionally, this model only ever suffers -2 AS when Firing Into Melee.",
                                         "All attacks made from this assault group must target the same model. Attacks with Burst may not be Aimed.",
                                         "Models with Guerilla Tactics may Squadlink from up to 8” away. This model only spends 1 AP to Break Away.",
                                         "At the start of this activation, this model may gain (x). If it does so, it loses 1 HP at the end of this activation.",
                                         "Each time this attack is selected, choose 1 of the following boosts to give this attack: +2 AS, +4 Power, or +4 Range. This model may spend additional AP when making this attack. For each additional AP, select 1 additional boost (each boost may be selected up to 2 times). These boosts only last for the current attack.",
                                         "Do not deploy this model as normal. During any Preparation Phase after Round 1 you may deploy this model by choose a point on the battlefield and performing a scatter roll from that point. Placing this model as close as as possible to the location of the scatter. Models with Ambush that share a squadlink value may deploy using 1 Scatter Roll, placing the first model on the point and the rest within 4”.",
                                         "After Deployment, this model may choose to make an immediate ranged attack at a target within 4”. This does count against the attack’s RF for the game round.",
                                         "This attack gains an additional power multiplier against the highest AR model hit. In the case of a tie, the attacking model decides who suffers the additional multiplier.",
                                         "This model always has Heavy Cover. Remove this counter at the start of this model's next activation.",
                                         "If this attack successfully infilcts damage upon a target, the target suffers an automatic hit from this attack immediately. This additional hit receives no Charge or Gang-Up bonuses, cannot be discarded or change targets due to special abilities, but can generate additional Continuous hits if it damages the target, and so on.",
                                         "Enemies within 4” may not remove Panic Counters. Enemies with Panic Counters activating within 4” must make a PS Check. On a failure they lose 1 AP.",
                                         "Once per round, when this model kills an enemy, it may make a PS Check. On a success, it may heal 1 HP.",
                                         "Twice per turn, this model may spend 1 AP to cast one of its psychogenics.",
                                         "This model does not deploy at the start of the game. During any Preparation Phase after round 1 this model may be deployed. When deployed, choose any point on the battlefield and place this model on that point.: This model does not deploy at the start of the game. During any Preparation Phase after round 1 this model may be deployed. When deployed, choose any point on the battlefield and place this model on that point.",
                                         "This model may never gain Panic Counters.",
                                         "This attack gains 1 additional power multiplier each time it is used after the first. These bonus power multipliers last until the next Lingering Effects Phase.",
                                         "While within 8” of this model, the (x) ability is ignored on models",
                                         "If an enemy is killed by this attack, all enemies within 4” of the model killed receive 1 Panic Counter.",
                                         "This model may spend 1 AP to give all enemies within 2” 1 Blind Counter and 1 Stun Counter. In addition, enemies with a smaller size are also knocked prone. Enemies at least two sizes smaller are automatically pushed directly away 6” as well.",
                                         "Each time a model with Oath of Fury is killed, all other models with Oath of Fury gain 1 Oath Counter. Models gain bonuses based on the number of Oath Counters they have (these effects are not cumulative).",
                                         "1 Counter: +2 AS to all attacks. 2 Counter: +1 AP, +2 AS, and the Unstoppable special ability",
                                         "Once per round, this model may select 1 weapon ability from any attack on a model it is in contact with (friendly or enemy). This attack gains the chosen weapon ability until the end of this model’s activation.",
                                         "Models hit by this attack gain 1 Disruption Counter.",
                                         "This model’s attacks that have a MAL Value suffer -2 MAL per Disruption Counter. During the Lingering Effects Phase, roll 1 d20 for each Disruption Counter, removing it on a roll of 10 or less.",
                                         "Living Models hit by this attack gain 1 Rot Counter.",
                                         "This model suffers -2 AR per Rot Counter. During the Lingering Effects Phase, roll 1 d20 for each Rot Counter, removing it on a roll of 10 or less.",
                                         "If this attack hits, all further attacks this model makes against the target automatically hit this activation unless a malfunction is rolled. These hits may not be Parried.",
                                         "When this model Squadlinks, any non-Character model it links with may receive +1 MV this activation. If this is done, that model gains 1 Stun Counter at the end of its activation.",
                                         "“Harpy” models this model squadlinks with may re-roll 1 attack roll this activation.",
                                         "Drillheads that squadlink with this model may re-roll 1 attack roll this activation.",
                                         "When this model activates it may power either its armor or specific attacks. If armor is selected, roll 1 additional d20 when making AR Saves, discarding the highest result. After this is done, if there is a result of 16 or higher, this model automatically fails its AR Save and loses 1 additional HP. If attack is selected, the attack must use the profile listed under its “Powered” version. These benefits last until the beginning of this model’s next activation.",
                                         "This model may spend 1 AP to give all enemies within 2” 1 Stun Counter. In addition, enemies with a smaller size are also knocked prone. Enemies at least two sizes smaller are automatically pushed directly away 6” as well.",
                                         "Friendly models beginning their activation within 8” of this model may automatically remove all Panic Counters for no AP cost. In addition, enemy effects can never modify their PS.",
                                         "This attack gains Extreme Damage when used as a charge attack.",
                                         "This model has multiple Stat Cards. At the start of this model’s activation it selects which Stat Card this model will use until its next activation.",
                                         "This model may spend 1 AP to place 1 Smoke Cloud anywhere completely within 6” inches. This may be done as an On-Hold Action.",
                                         "This terrain piece is represented by a Blast(3) Template. Models in a Smoke Cloud gain Heavy Cover. All melee attacks targeting models in a Smoke Cloud suffer -4 AS. Remove this terrain piece at the end of the next Lingering Effects Phase.",
                                         "During the Preparation Phase, select 1 enemy within 12” and line of sight. Models gain +1 AS and +1 PW to attacks made against that enemy this round.",
                                         "While within 4” of this model, Grand Templar Marius gains (x).",
                                         "When this model powers its Armor via Power Generator it gains +1 MV and may ignore models and terrain when moving this activation.",
                                         "While not prone, and within 1” of another model with Shield Formation, this model gains +2 AR.",
                                         "Once per activation, this model may spend 1 AP to automatically remove friendly model in contact with it from play as a casualty. If it does so, this model heals 1 HP.",
                                         "When deployed, (x) Pud Roamer models are also deployed for free within 6” of this model.",
                                         "This model’s melee attacks roll a number of dice to hit equal to their current remaining HP.",
                                         "This model does not count for friendly Primary or Secondary Objective purposes, and cannot benefit from or count for Gang-Up bonuses. All Brood Mind models must activate as a single Squadlink when activated, ignoring the distance between them. They may not otherwise Squadlink in any way.",
                                         "This model may spend 1 AP when in contact with a wounded friendly model to heal 1 HP to that model. Remove this model from play immediately after.",
                                         "For 1 AP this model may gain 1 Burrow Counter.",
                                         "This model has -4 DF and +2 AR, but cannot make attacks. You may remove all Burrow Counters at the start of this model’s activation. A model may only have 1 Burrow Counter at any time.",
                                         "Whenever this model’s attack(s) inflicts 1 or more HP of damage upon an enemy model it is engaged with, it may attempt a PS Check. If successful, it may heal 1HP OR gain 1 Energize Counter.",
                                         "Energize Counter is automatically discarded at the beginning of a model’s activation to give it +1 AP.",
                                         "While a model with Scavenge is in play, whenever a model is killed or removed from play, place 1 Scavege Counter in contact before it is removed. Any model with Scavenge may automatically pick up Scavenge Counters by moving over them.",
                                         "This model gains +1 AR , and +1 AS and +1 PW to all attacks,for each Scavenge Counter. If this model is killed or removed from play, place all Scavenge Counters it has in contact with it before it is removed. A model may have up to 3 Scavenge Counters at any time.",
                                         "This model may not be targeted or affected by Psychogenics.",
                                         "This model automatically passes the PS Check in order to Evade while On Hold. Additionally, enemy models may never target this model with an Aimed Ranged Attack.",
                                         "This model has (y). While (x) is within 8” of this model, it gains (y).",
                                         "This model may, during its activation, spend 1 AP to immediately remove all Fire Counters from itself and other models within 8”.",
                                         "While engaged with an enemy, other friendly models gain +1 AS and +1 PW to melee attacks against that enemy. Distraction is not cumulative.",
                                         "If this model ends its activation unengaged it automatically goes On Hold.",
                                         "Once per turn, this model may spend 1 AP to cast one of its psychogenics.",
                                         "Once per round, while in contact with an Objective Marker, this model may make a PS Check. If that check is successful it gains 1 Scavenge Counter.",
                                         "Whenever this model kills an enemy that has a Bleed Counter, it gains 1 Bloodlust Counter.",
                                         "When this model would lose HP, it may discard this counter to prevent losing that HP. A model may only have 1 Bloodlust Counter at any time.",
                                         "Enemy models within 2” of this model suffer -1 MAL to each attack with a MAL Value. Ghost in the Machine is cumulative.",
                                         "When this model is deployed, select up to 6 “Buzzblade” models. Upgrade those models to “Dominique’s Chalica”.",
                                         "Each time this model is targeted by attacks, before attack dice are rolled, it may make a PS Check. On a success, the enemy targeting this model gains 1 Disruption Counter.",
                                         "(x) times per game, when a malfunction is rolled from a psychogenic, that model may ignore the malfunction. This ability functions even if this model is killed.",
                                         "Enemy models in contact with this model suffer -1AS and -1PW when performing melee attacks.",
                                         "When this model is deployed, choose up to 6 (x). Those models gain (y).",
                                         "At the start of each activation, this model must make a PS Check. On a failure it does not activate as normal, but instead uses its activation to immediately move directly toward the nearest model with a different model name and use any remaining AP to perform melee attacks on that model.",
                                         "This attack may re-roll misses if targeting a model that already possesses one or more Toxic Counters.",
                                         "Enemy models suffer -1 AS and -1 PW while within 2” of this model.",
                                         "When this model is deployed, select up to 6 “Buzzblade” models. Upgrade those models to either “Charity’s Might” or “Charity’s Zeal”.",
                                         "Once per game, during the Preparation Phase, this model may make a PS Check. On a success, select up to 6 friendly Trueborn models. They may each immediately make 1 move action (this cannot result in a charge).",
                                         "Enemies never gain bonuses for Charging or Gang-Up against this model. This model may never be knocked prone by enemies and ignores the Rough and Dangerous keywords of terrain pieces.",
                                         "Other non-Trueborn models this model squadlinks with may gain (x) this activation. If this is done, that model must make a PS Check at the end of its activation. On a failure, it loses 1 HP. A model may only benefit from Taskmaster once per activation.",
                                         "Once per activation, this model may spend 1 AP to place 1 Shard Field(x) anywhere completely within 2” inches. This may be done as an On-Hold Action.",
                                         "This terrain piece is represented by a Blast(1) Template. Any model entering, or beginning their activation within, the Shard Shield suffers (x), and then the Shard Field is removed.",
                                         "Once per enemy activation, make an AS Check when targeted with an Attack gained from a Charge. Success allows you to move attacking model up to 2” in any direction before attack is made. If this takes the attack out of range, it automatically misses (but still rolls to check for Malfunction).",
                                         "Once per game, in the Preparation Phase, this model may attempt a PS Check. If successful, the area within 4” of friendly Trueborn models are treated as having the Rough Terrain Keyword for enemy models. Terrain already possessing the Rough Terrain Keyword are treated as having the Dangerous Terrain Keyword. These effects last until the Lingering Phase.",
                                         "This model ignores the Rough and Dangerous terrain keywords. Additionally, during its activation, this model gains a cumulative +1MV for each movement action after the first. These movements CAN be Charge Actions. The model’s MV stat returns to normal at the end of its activation.",
                                         "Whenever a friendly model within 8” of this model fails a PS Check for any reason, it may choose to gain an Immobilized Counter to re-roll the failure. A model may only re-roll a single PS Check with Centered Focus once per failed Check.",
                                         "If this attack Malfunctions, this model, and all other models within 1”, suffer (x).",
                                         "Each Preparation Phase roll a d20. 10 or less and there is no effect; 11+ and the model suffers 1 HP of damage automatically.",
                                         "This model’s move actions ignore the rules for Breaking Free and may result in a Charge (if contacting a new enemy model). However, it may never interact with Objective Markers in any fashion and is never considered to be “in contact” with Objective Markers.",
                                         "If this attack kills an enemy, place 1 “Ember” within 4” of this model",
                                         "Once per game, during the Preparation Phase, this model may make a PS Check. On a success, all friendly Trueborn models may re-roll 1 failed attack roll when making charge attacks this round.",
                                         "This model ignores the normal method for choosing psychogenics. Instead it chooses its psychogenic powers from any one of the elemental castes (Air, Earth, Fire, Ice and Shadow), chosen before deployment.",
                                         "This model may never gain Fire Counters. Enemies hitting this model with melee attacks gain 1 Fire Counter at the end of their activation.",
                                         "This model ignores Shard Fields.",
                                         "Friendly models with Emberspark within 4” may:</br>• Kill this model when they suffer damage to prevent 1 damage.</br>• Kill this model to re-roll 1 failed attack roll.</br>• Kill this model when they hit an enemy with a melee attack to give that attack +2 PW.",
                                         "This model’s attacks may never be discarded, its weapon abilities never ignored, and damage it deals cannot be reduced.",
                                         "While within 2” of this model, enemies suffer -2 AS.",
                                         "Once per game, during the Preparation Phase, this model may make a PS Check. On a success, place 1 Blind Counter on up to 4 enemies.",
                                         "Once per activation, this model may spend 1 AP to give all enemies within 2” 1 Blind Counter.",
                                         "Any model moving into base contact or starting their activation within 1” of this model must pass a PS Check or gain 1 Panic Counter. Models that already possess a Panic Counter that fail this check suffer an automatic PW: 4 hit.",
                                         "This model may never gain Panic Counters. This model’s PS may never be modified by enemy effects.",
                                         "If this attack kills an enemy, you may place this model anywhere within 6” after the attack is resolved.",
                                         "Each time this model kills an enemy model with a melee attack, it gains 1 Death Echo Counter.",
                                         "This model may spend 1 AP and resolve this counter to have all enemies within 2” make a PS Check. On a failure they gain 1 Panic Counter. If they already had a Panic Counter they instead suffer 1 automatic damage. A model may only have 1 Death Echo Counter at any time.",
                                         "Models of Large size or larger with the Non-Living special ability reduced to 0 HP while within 8” of this model places 1 30mm Scrap Counter in base contact with it before being removed from play.",
                                         "Any model with the Reconstruction special ability in contact with this Counter can spend 1 AP to remove it and place a new Menial Bot model anywhere in base contact with it.",
                                         "This model receives an additional +1 AS and +1 PW from Gang-Up.",
                                         "Friendly models within 8” of this model add +1 to their MAL numbers (ie: 17 to 18, 18 to 19, etc.), to a maximum adjusted MAL of 20. The effects of Diagnostics are cumulative.",
                                         "This model may choose to lose 1 HP in order to allow any one friendly model it is squadlinking with to ignore a single MAL at the time it is rolled.",
                                         "During this model’s activation, you may discard 1 Bio-Energy Counter to trigger Bio-Enhance(x). If you do, this model gains (x) until the end of its activation. Each instance of Bio-Enhance may be triggered once per activation.",
                                         "Kukulkani power counter.",
                                         "If this attack kills an enemy, add 1 Bio-Energy to your Bio-Energy Pool.",
                                         "This model may cast Kukulkani Rituals. In addition to its chosen Ritual, this model always has access to the Gaze of the Moon Goddess ritual.",
                                         "This model may spend 1 AP, discard 1 Bio-Energy Counter, and remove 1 Weakened Resolve Counter from any model it is currently Squadlinking with.",
                                         "This model may cast Kukulkani Rituals.",
                                         "This model may cast Kukulkani Rituals, and may select 1 additional Ritual to have active (and may switch these Rituals as per the Technomancy rules). At the start of each Preparation Phase, add 1 Bio-Energy Counter to your Bio-Energy pool. When this model is killed, add 4 Bio-Energy Counters to your Bio-Energy Pool.",
                                         "This model may treat all areas of a terrain piece with the Levels keyword as having the Climbable keyword.",
                                         "At the start of each Preparation Phase, add 1 Bio-Energy Counter to your Bio-Energy pool.",
                                         "When this model is killed, it may make a PS Check. On a success add 1 Bio-Energy to your Bio-Energy pool.",
                                         "This model may only be chosen to be included in a Force as long as an equal number of models with the Lunar Balance special ability are also chosen to be included.",
                                         "This model may only be chosen to be included in a Force as long as an equal number of models with the Solar Balance special ability are also chosen to be included.",
                                         "This model may use the listed (x) Kukulkani Ritual, once per activation."
                                         ))
