---
title: "Army Quick Reference"
author: "Samaria"
output: html_document
params:
  Table: NA
  Title: "Kukulkani"
  CurrentPoint: "500"
  MaxPoint: "750"
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

```{r armyRef, echo = FALSE, results = 'asis'}
datatable(
  cbind(' ' = 'Add-Ons &oplus;',  params$Table), escape = -2,
  options = list(
    dom = 't',
    columnDefs = list(
      list(visible = FALSE, targets = c(0, 7, 8)),
      list(orderable = FALSE, className = 'details-control', targets = 1)
    )
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});
  var format = function(d) {
    return '<div style=\"background-color:#eee; padding: .5em;\"> <strong>Upgrades/BioGens:</strong> ' +
            d[7] + '</br><strong>Psychogenics/Rituals:</strong> ' + d[8] + '</div>';
  };
  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('Add-Ons &oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('Add-Ons &CircleMinus;');
    }
  });"
  ))
```